# Generated by Django 4.0.5 on 2022-06-16 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comment_posted_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 23, 23, 49, 872302)),
        ),
    ]
