# Generated by Django 4.0.5 on 2022-06-15 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_posted_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items_in_watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 0, 45, 523078)),
        ),
    ]
