# Generated by Django 4.0.5 on 2022-06-15 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_posted_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='related_listing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 54, 56, 765569)),
        ),
    ]
