# Generated by Django 4.0.5 on 2022-06-15 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_related_listing_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 58, 28, 205792)),
        ),
    ]
