# Generated by Django 4.0.5 on 2022-06-15 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 11, 6, 17, 388674)),
        ),
    ]
