# Generated by Django 4.0.5 on 2022-06-16 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_posted_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 23, 57, 25, 949606)),
        ),
    ]
