# Generated by Django 4.0.5 on 2022-06-16 05:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_comment_posted_datetime_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 0, 20, 27, 617479)),
        ),
    ]
