# Generated by Django 4.0.5 on 2022-06-18 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_listing_alter_comment_posted_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 15, 2, 50, 853457)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.category'),
        ),
    ]
