# Generated by Django 4.0.5 on 2022-06-18 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_alter_comment_posted_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 15, 6, 44, 886910)),
        ),
    ]
